[package]
name = "rsbot"
version = "0.2.1"
authors = ["LEGOlord208 <LEGOlord208@krake.one>"]

description = "Simulate keypresses with Rust!"
license = "MIT"
repository = "https://github.com/legolord208/rsbot"

[dependencies]
libc = "0.2"
